[metadata]
name = llmrouter
version = 0.1.0
description = Minimal LLMRouter MVP
long_description = file: README.md
long_description_content_type = text/markdown
author = Amar
license = MIT
classifier =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License

[options]
packages = find:
include_package_data = True
python_requires = >=3.8

[options.packages.find]
where = .
