[metadata]
name = llmrouter
version = 0.1.0
description = Minimal LLMRouter MVP
long_description = file: README.md
long_description_content_type = text/markdown
author = Amar
author_email = amar@example.com
license = MIT
url = https://github.com/amar8737/LLMRouter
project_urls =
    Source = https://github.com/amar8737/LLMRouter
    Tracker = https://github.com/amar8737/LLMRouter/issues
classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    License :: OSI Approved :: MIT License
    Topic :: Software Development :: Libraries

[options]
packages = find:
include_package_data = True
python_requires = >=3.8

[options.packages.find]
where = .
